project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    left:
      - text: "Home"
        href: "index.qmd"
      - text: "In class_Ex"
        menu: 
          - text: "In class_Ex 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "In class_Ex 4" 
            href: "In-class_Ex/In-class_Ex04/In-class_Ex04.html"
      - text: "Hands on_Ex"
        menu: 
          - text: "Hands on_Ex 1"
            href: "Handson_Ex/Handson_Ex01/Handson_Ex01.html"
          - text: "Hands on_Ex 3"
            href: "Handson_Ex/Handson_Ex03/Handson_Ex03.html"
          - text: "Hands on_Ex 4"
            href: "Handson_Ex/Handson_Ex04/Handson_Ex04.html"
          - text: "Hands on_Ex 5"
            href: "Handson_Ex/Handson_Ex05/Handson_Ex05.html"
      - text: "Take Home_Ex"
        menu: 
          - text: "Take Home_Ex 1"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
      - text: "Visual Analytic Project"
        href: "Visual_Analytic_Project/MC2.html"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

